# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sudoku' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sudoku

  #AFN
  pod 'AFNetworking'

  # DroiCoreSDK核心元件    
  pod 'DroiCoreSDK'    
    # 执行CoreSDK安裝script file
    post_install do |installer|
      require './Pods/DroiCoreSDK/scripts/postInstall.rb'
      DroiCoreParser.installParser()
    end


end
